#!/usr/bin/env bash
# Regenerates _data/localtier.yml by READING EACH EDITION'S OWN SOURCE.
#
# The website states: "This table is generated from an audit that reads each
# repository's own source. It cannot claim a capability the code does not
# contain." This script is what makes that sentence true. Before 2026-08-25 the
# file claimed to be generated by a script that did not exist in the repo, and
# it asserted australia = "wired" when australia shipped no way to switch it on.
#
# A local tier needs BOTH halves to be real:
#   runtime  — brain/llm.py contains the local provider branch
#   setup    — connect_local.py ships, so a user can actually turn it on
#
#   wired         both halves present
#   runtime-only  runtime present, no shipped setup path  -> NOT a user capability
#   planned       neither
#
# Usage: ./audit-localtier.sh [path-to-sibling-repos]   (default: ..)
set -euo pipefail

BASE="${1:-..}"
OUT="_data/localtier.yml"

declare -a SLUGS=(india uk eu usa singapore hongkong dubai australia)
declare -A NAMES=(
  [india]="India" [uk]="United Kingdom" [eu]="European Union"
  [usa]="United States" [singapore]="Singapore" [hongkong]="Hong Kong"
  [dubai]="Dubai · DIFC" [australia]="Australia"
)

stamp="$(date +%Y-%m-%dT%H:%M:%S%z)"
tmp="$(mktemp)"
{
  echo "# GENERATED — do not hand-edit."
  echo "# Written by audit-localtier.sh, which reads each repo's own source."
  echo "# Regenerate before every publish. Source of truth is the code, not this file."
  echo "# generated_at: ${stamp}"
  echo ""
} > "$tmp"

fail=0
for slug in "${SLUGS[@]}"; do
  repo="${BASE}/ai-brain-${slug}"
  pkg="${repo}/ailawfirm_${slug}"
  [ -d "$pkg" ] || pkg="${repo}/aibrain_${slug}"   # survives the 2026-08 rename

  if [ ! -d "$pkg" ]; then
    tier="unknown"; fail=1
    echo "  !! ${slug}: package not found under ${repo}" >&2
  else
    runtime=no; setup=no
    grep -q '_is_local_provider' "${pkg}/brain/llm.py" 2>/dev/null && runtime=yes
    [ -f "${pkg}/connect_local.py" ] && setup=yes
    if   [ "$runtime" = yes ] && [ "$setup" = yes ]; then tier="wired"
    elif [ "$runtime" = yes ];                       then tier="runtime-only"
    else                                                  tier="planned"
    fi
    printf '  %-11s runtime=%-3s setup=%-3s -> %s\n' "$slug" "$runtime" "$setup" "$tier" >&2
  fi

  {
    echo "- slug: ${slug}"
    echo "  name: \"${NAMES[$slug]}\""
    echo "  local_tier: \"${tier}\""
  } >> "$tmp"
done

mv "$tmp" "$OUT"
echo "wrote ${OUT} at ${stamp}" >&2
exit $fail
